version: '3.8'

services:
  wechat:
    build: .
    container_name: wechat-app
    ports:
      - "8081:8081"
    volumes:
      - ./config/app.yml:/app/config/app.yml      # 挂载配置文件 宿主机目录:容器目录
      # todo 需要将对应的路径修改为自己的路径
      - /Users/jiang/data/scripts:/data/scripts   # 挂载Python脚本 宿主机目录:容器目录
      # 把 wechat 容器的 /data/wechat 目录映射到宿主机 挂载 wechat 目录到宿主机的一个共享路径，用来通过nginx访问文件
      - /Users/jiang/data/wechat:/data/wechat  # 意思就是将宿主机的 /Users/jiang/data/wechat 目录挂载到容器的 /data/wechat 目录上
    networks:
      - common-app-net

volumes:
  mysql_data:

networks:
  common-app-net:
    external: true