app: wechat
port: 8081
debug: true
db:
  wechat:
    dialect: mysql
    dsn: root:123456@tcp(mysql:3306)/wechat?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
log:
  outputs:
    - stdout
    - ./logs/api.log