app: wechat
port: 8081
debug: true
db:
  wechat:
    dialect: mysql
    dsn: root:123456@tcp(mysql:3306)/wechat?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
mini:
  app_id: wx1234567890123456
  app_secret: 12345678901234567890123456789012
log:
  outputs:
    - stdout
    - ./logs/api.log