app: wechat
port: 8083
debug: true
db:
  wechat:
    dialect: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/wechat?charset=utf8mb4&parseTime=True&loc=Local
log:
  outputs:
    - stdout
    - ./logs/api.log